config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  get 'products/:category_id/search', to:"products#search" , as:'products_search'
  resources :customers
  resources :products
  resources :shipping_addresses
  resources :order_histories,only: [:index,:new,:create,:show,:edit,:update]

  get 'carts/confirm' => 'carts#confirm'

  get 'carts/complete' => 'carts#complete'

  delete 'carts/destroy_all' => 'carts#destroy_all'
  resources :carts, only: [:index,:new,:create,:edit,:update,:destroy]


  namespace :admin do
    root :to => 'products#top'
    resources :products
    resources :order_histories
    get 'order_histories/:customer_id/search', to:"order_histories#search" , as:'order_histories_search'
    resources :customers do
      patch :toggle_status
    end
    resources :categories do
      patch :toggle_status
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :customer
	belongs_to :product

    def get_product
	  Product.find(self.product_id)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_customer!
	def index
		@carts =  current_customer.carts
	end

    def new
	  @order_history = OrderHistory.new
	  @new_address = ShippingAddress.new
    end


	def create

		if current_customer.carts.where(product_id: params[:cart][:product_id].to_i).empty?
		@cart = Cart.new(cart_params)
		@cart.customer_id = current_customer.id
  	    @cart.save
	   else
		@cart = current_customer.carts.find_by(product_id:params[:cart][:product_id].to_i)
		@cart.update(number: params[:cart][:number].to_i + @cart.number)
        end
        redirect_to products_path
	end


    def confirm
      @carts = current_customer.carts
      @order_history = OrderHistory.new
      @order_history.payment_method = params[:order_history][:payment_method]
      @new_address = ShippingAddress.new

      if params[:selected_button] == "customer_address"
        @order_history.zipcode = current_customer.zipcode 
      	@order_history.address = current_customer.address
      	@order_history.name = current_customer.last_name + current_customer.first_name

      end
      if  params[:selected_button] == "another_address"
      	@shipping_address =  ShippingAddress.find(params[:order_history][:customer_id])
        @order_history.zipcode = @shipping_address.shipping_zipcode
        @order_history.address = @shipping_address.shipping_address
        @order_history.name = @shipping_address.name
      end
      if  params[:selected_button] == "new_customer_address"
	  	  @order_history.zipcode = params[:order_history][:shipping_address][:shipping_zipcode]
      	@order_history.address = params[:order_history][:shipping_address][:shipping_address]
      	@order_history.name = params[:order_history][:shipping_address][:name]
      end
        @selected_button = params[:selected_button]
        @order_history.make_order_details(current_customer.carts)
    end

    def complete

    end

	def update
		@cart = Cart.find(params[:id])
		@cart.update(cart_params)
		redirect_to carts_path
	end

	def destroy
		@cart = Cart.find(params[:id])
        @cart.destroy
        redirect_to carts_path
	end

	def destroy_all
		@carts =  current_customer.carts
		@carts.destroy_all
		redirect_to products_path
	end

 private
    def cart_params
      params.require(:cart).permit(:number,:product_id)
    end
  end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/complete.html.erb
<%= render 'layouts/c_header' %>
<div class="thanks w-100 h-100">
<p class="h3 text-center">ご購入ありがとうございました！</p>	
</div>

app/views/carts/confirm.html.erb
<%= render 'layouts/c_header' %>
<div class="container">
    <h3>注文情報確認</h3>
    <table class="table table-bordered text-center">
        <thead>
            <tr>
                <th>商品名</th>
                <th>単価(税)</th>
                <th>数量</th>
                <th>小計</th>
            </tr>
        </thead>
        <!-- 関数 get_product/tax_includeはcart.rb/product.rbに定義 -->
        <% @total_price = 0 %>
        <tbody>
            <% (@carts).each do |cart| %>
            <tr>
                <td class="align-middle">
                    <%= attachment_image_tag cart.get_product , :product_image, :fill,60,60 %>
                    <%= cart.get_product.product_name %>
                </td>
                <td class="align-middle">
                    <%= cart.get_product.tax_include.floor %>
                <td class="align-middle">
                    <%= cart.number.floor %>
                </td>
                <td class="align-middle">
                    <%= (cart.get_product.tax_include * cart.number).floor %>
                </td>
            </tr>
            <% @total_price += cart.product.tax_include   * cart.number
        %>
            <% end %>
        </tbody>
    </table>
    <table class="table table-bordered text-center">
        <tr>
            <td>送料</td>
            <td>800</td>
        </tr>
        <tr>
            <td>商品合計</td>
            <td>
                <%= @total_price.floor %>
            </td>
        </tr>
        <tr>
            <td>請求金額</td>
            <td>
                <%= (@total_price + 800).floor %>
            </td>
        </tr>
    </table>
    <div class="important info mt-5">
        <h5>支払方法</h5>
        <p>
            <%= @order_history.payment_method_i18n %>
        </p>
        <h5>お届け先</h5>
        <p>
            <%= @order_history.zipcode %>
            <%= @order_history.address %>
            <%= @order_history.name %>
        </p>

        <%= form_for(@order_history,url: order_histories_path, method: :post) do |f| %>
        <%= f.hidden_field :payment_method, :value => @order_history.payment_method %>
        <%= f.hidden_field :customer_id, :value => current_customer.id %>
        <%= f.hidden_field :zipcode, :value => @order_history.zipcode %>
        <%= f.hidden_field :address, :value => @order_history.address %>
        <%= f.hidden_field :name, :value => @order_history.name %>
        <%= f.hidden_field :order_status, :value => '入金待ち' %>
        <%= f.hidden_field :total_price, :value =>  @total_price %>
        <%= f.hidden_field :shipping_fee, :value => 800 %>

        <%= f.fields_for :order_details do |dt| %>
        <%= dt.hidden_field :order_history_id%>
        <%= dt.hidden_field :product_id %>
        <%= dt.hidden_field :tax_included%>
        <%= dt.hidden_field :number %>
        <%= dt.hidden_field :prepare_status %>

        <% end %>
        <%= hidden_field_tag :selected_button, @selected_button %>
        <%= f.submit "購入を確定する", class:'btn btn-md btn-primary mt-2' %>
        <% end %>
    </div>
</div>
<!-- 注文情報確認画面は複数のカートの情報を扱うので、showページではない。Confirmアクション等を作るのが○
 -->
<!--  Cartssコントローラのnewアクションは要修正 -->
<!-- 注文情報確認テーブルの情報は全て、Cartsモデルと紐づいているため、Cartsモデルから作ったインスタンス変数を用いて、each文で表示させる -->
<!-- 税金カラムは作った方が良い。作るなら、注文履歴テーブル
税金は初期値を入力する -->
<!-- 演算の記述方法は２つある。Viewにベタ書きするか、Controllerに変数を定義して、Viewで表示させるか -->

app/views/carts/index.html.erb
<%= render 'layouts/c_header' %>
<div class="container mt-5">
<h2>ショッピングカート</h2>
  <button type="button" class="btn btn-danger btn-md">
    <%= link_to "空にする",carts_destroy_all_path, method: :delete %>
  </button>


    <table class="table table-hover mt-3">
      <tbody>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th></th>
          <th></th>
        </tr>
        <% total=0 %>
      <% @carts.each do |cart| %>
        <tr>
          <td><%= attachment_image_tag cart.product,:product_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :width => "60", :height => "60" %><%= cart.product.product_name %></td>
          <td><%= price = (cart.product.tax_excluded * 1.1).floor %></td>
          <td><%= form_for(cart,url:cart_path(cart), html: {method: "patch"}) do |f| %>
              <%= f.text_field :number %><%= f.submit "数量を変える" %>
              <% end %>
          </td>
          <td><%= price * cart.number %></td>
          <td><button type="button" class="btn btn-success btn-sm">
            <%= link_to "destroy",cart_path(cart), method: :delete %>
          </button></td>
        </tr>
        <% total = price * cart.number + total %>

       <% end %>
      </tbody>
    </table>
  <div class="text-right">
    <h3 class="mb-4">合計金額<%= total %>円</h3>
    <%= link_to '買い物を続ける', products_path, class: "btn btn-primary mr-3" %>
    <%= link_to '情報入力へ進む', new_cart_path, class: "btn btn-primary" %>
  </div>

  
</div>

app/views/carts/new.html.erb
<%= render 'layouts/c_header' %>
<div class="container mt-5">
    <h3 class="mb-4">購入情報入力</h3>
    <%= form_for(@order_history,url: carts_confirm_path,method: :get) do |f| %>
    <h4>支払方法入力</h4>
    <!-- enum(見た目は文字列、integerとして管理できる)を使用 -->
    <label>
        <%= f.radio_button :payment_method, :credit %>クレジットカード
    </label>
    <label>
        <%= f.radio_button :payment_method, :bank %>銀行振込
    </label>
    <h4 class="mt-2">お届け先</h4>
    <label>
        <%= radio_button_tag("selected_button","customer_address") %>ご自身の住所
    </label>
    <p>〒<span>
            <%= current_customer.zipcode %>
            <%= current_customer.address %>
            <%= current_customer.last_name %>
            <%= current_customer.first_name %></span></p>
    <label>
        <%= radio_button_tag("selected_button","another_address") %>登録済住所から選択
    </label><br>
    <%= f.label :customer_id , class:'sr-only' %>
    <%= f.collection_select :customer_id, current_customer.shipping_addresses,:id, :full_address  %><br>
    <!--     customer_idの箇所はローカル変数fにあるカラムであればどれでも○
 -->
    <!-- idをビューから、コントローラに渡している -->
    <label class="mt-4">
        <%= radio_button_tag("selected_button","new_customer_address") %>新しいお届け先
    </label>
    <%= f.fields_for(@new_address) do |na| %>
    <p>郵便番号
        <%= na.text_field :shipping_zipcode %><span>ハイフンなし</span></p>
    <p>住所
        <%= na.text_field :shipping_address %>
    </p>
    <p>宛名
        <%= na.text_field :name %>
    </p>
    <% end %>
    <%= f.submit "確認画面へ進む",class:'mt-2'%><br>
    <% end %>
</div>
<!-- ラジオボタンを使用するためには、labelタグが必須 -->
<!-- OrderHistoriesテーブル、宛名カラムをnameに統一 -->