config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  get 'products/:category_id/search', to:"products#search" , as:'products_search'
  resources :customers
  resources :products
  resources :shipping_addresses
  resources :order_histories,only: [:index,:new,:create,:show,:edit,:update]

  get 'carts/confirm' => 'carts#confirm'

  get 'carts/complete' => 'carts#complete'

  delete 'carts/destroy_all' => 'carts#destroy_all'
  resources :carts, only: [:index,:new,:create,:edit,:update,:destroy]


  namespace :admin do
    root :to => 'products#top'
    resources :products
    resources :order_histories
    get 'order_histories/:customer_id/search', to:"order_histories#search" , as:'order_histories_search'
    resources :customers do
      patch :toggle_status
    end
    resources :categories do
      patch :toggle_status
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates :name, presence: true, uniqueness: true
	enum status: { 無効: 0, 有効: 1} #enumの記述方式

# toggle_statusメソッドを定義(admin_categoryのcontrollerで使用)
	def toggle_status
		if status == "有効"
			status = 0
		else
			status = 1
		end
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	before_action :authenticate_admin!

	def index
		@categories = Category.all
		@category = Category.new
	end
	def new
	end
	def create
		@category = Category.new(category_params)
			if @category.save
				redirect_to admin_categories_path
			else
				@categories = Category.all
				render :index
			end
	end
	def edit
		@category = Category.find(params[:id])
	end
	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
		redirect_to admin_categories_path
		else
			render :edit
		end
	end

	#カテゴリーの有効・無効を切り替えるためのアクション、アクション内の.toggle_statusはカテゴリーのモデルで定義
	def toggle_status
		@category = Category.find(params[:category_id])
		 @category.update(status: @category.toggle_status)
		redirect_to admin_categories_path
	end

	private
  def category_params
  	params.require(:category).permit(:name, :status)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<%= render 'layouts/a_header' %>
    <h2>ジャンル登録/編集</h2>
    <% if @category.errors.any? %>
<div id="error_explanation">
    <ul>
        <% @category.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
    <%= form_for(@category, url: admin_category_path(@category.id)) do |f| %>
      <h4>ジャンル</h4>
      <%= f.text_field :name ,class:"col-xs"%>
      <%= f.submit '保存する',class:"col-xs btn btn-primary"%>
    <% end %>

app/views/admin/categories/index.html.erb
<%= render 'layouts/a_header' %>
<div class="container mt-5">
<h2>ジャンル登録/一覧</h2>
<% if @category.errors.any? %>
<div id="error_explanation">
    <ul>
        <% @category.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<%= form_for(@category, url: admin_categories_path) do |f| %>
<h4>ジャンル</h4>
<%= f.text_field :name ,class:"col-xs"%>
<%= f.submit '追加',class:"col-xs btn btn-primary"%>
<% end %>
<table class="table table-hover mt-3">
    <tbody>
        <tr>
            <th>ジャンル</th>
            <th></th>
            <th></th>
        </tr>
        <% @categories.each do |category| %>
        <tr>
            <td>
                <%=category.name %>
            </td>
            <!------- #カテゴリーのステータス(有効・無効)を切り替えるための記述 ------->
            <td>
                <% if category.status == "有効" %>
                <button type="button" class="btn btn-danger btn-sm btn-default">
                    <%= link_to "無効にする", admin_category_toggle_status_path(category), :style =>"color:white", method: :patch %>
                </button>
                <% else %>
                <button type="button" class="btn btn-primary btn-sm">
                    <%= link_to "有効にする", admin_category_toggle_status_path(category), :style =>"color:white", method: :patch %>
                </button>
                <% end %>
                <button type="button" class="btn btn-primary btn-sm">
                    <%= link_to "編集する", edit_admin_category_path(category.id), :style =>"color:white" %>
                </button>
        </tr>
        <% end %>
    </tbody>
</table>    
</div>