config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  get 'products/:category_id/search', to:"products#search" , as:'products_search'
  resources :customers
  resources :products
  resources :shipping_addresses
  resources :order_histories,only: [:index,:new,:create,:show,:edit,:update]

  get 'carts/confirm' => 'carts#confirm'

  get 'carts/complete' => 'carts#complete'

  delete 'carts/destroy_all' => 'carts#destroy_all'
  resources :carts, only: [:index,:new,:create,:edit,:update,:destroy]


  namespace :admin do
    root :to => 'products#top'
    resources :products
    resources :order_histories
    get 'order_histories/:customer_id/search', to:"order_histories#search" , as:'order_histories_search'
    resources :customers do
      patch :toggle_status
    end
    resources :categories do
      patch :toggle_status
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	belongs_to :category
	has_many :carts, dependent: :destroy
	has_many :order_details, dependent: :destroy
	has_many :order_histories, :through => :order_details
	validates :product_name, presence: true, uniqueness: true
	validates :caption, presence: true
	validates :tax_excluded, presence: true
	validates :sale_status, presence: true
	validates :category_id, presence: true
	enum sale_status:[:販売中, :販売停止中]

	def tax_include
		self.tax_excluded * 1.1
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def top
     @order_histories = OrderHistory.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  	redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      redirect_to admin_product_path(product.id)
    else
      redirect_to admin_products_path
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
  	params.require(:product).permit(:product_image, :caption,:product_name,:category_id,:tax_excluded,:sale_status)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def index2
  end

  def search
    @products2 = Product.where(category_id: params[:category_id])
    @categories = Category.all
    render :index2
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admin_products_path
  end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
  end

  def edit
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      redirect_to admin_product_path(product.id)
    else
      render "admin/products/edit.html.erb"
    end
  end



  private
  def product_params
  	params.require(:product).permit(:product_image, :caption,:product_name,:category_id,:tax_excluded,:sale_status)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<%= render 'layouts/a_header' %>
<div class="container">
    <div class="row">
        <div class="col-lg-4 mt-1">
            <h1>商品編集画面</h1>
            <%= attachment_image_tag @product, :product_image, :fill, 300,300, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "300", :height => "300" %>
            <%= form_for(@product) do |f| %>
            <%= f.attachment_field :product_image, class: "btn btn-sm btn-block btn-primary mb-1" %>
        </div>
        <div class="col-lg-8 mt-5">
            <table>
                <tr>
                    <td><label>商品名</label></td>
                    <td>
                        <%= f.text_field :product_name %>
                    </td>
                </tr>
                <tr>
                    <td><label>商品説明</label></td>
                    <td>
                        <%= f.text_field :caption %>
                    </td>
                </tr>
                <tr>
                    <td><label>ジャンル</label></td>
                    <td><%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "選択してください" %>
                    </td>
                <tr>
                    <td><label>税抜価格</label></td>
                    <td>
                        <%= f.text_field :tax_excluded %>円</td>
                </tr>
                <tr>
                    <td><label>販売ステータス</label></td>
                    <td>
                        <%= f.select :sale_status, Product.sale_statuses.keys, :selected=>Product.sale_statuses[@product.sale_status] %>
                    </td>
            </table>
            <%= f.submit "変更を保存", class: "btn btn-sm btn-primary mt-2" %>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/products/index.html.erb
<%= render 'layouts/a_header' %>
<div class="container mt-5">
  <h1>商品一覧画面</h1>
  <%= link_to new_admin_product_path do %>
    <h1 class="fas fa-plus-circle"></h1>
  <% end %>
    <table class="table table-hover mt-2">
      <tbody>
        <tr>
          <th>商品</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
            <% @results1.each do |product| %>
        <tr>
          <td><%=product.id%></td>
          <td>
          <%= link_to admin_product_path(product.id) do %>
            <%=product.product_name%>
          <% end %>
          </td>
          <td><%=product.tax_excluded%> 円</td>
          <td><%=product.category.name %></td>
          <td><%=product.sale_status%></td>
        </tr>
            <% end %>
      </tbody>
    </table>
    <%= paginate @results1 %>
</div>

app/views/admin/products/new.html.erb
<%= render 'layouts/a_header' %>

<div class="container mt-5">
<% if @product.errors.any? %>
<div id="error_explanation">
    <ul>
        <% @product.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>

<%= form_for(@product,url:admin_products_path) do |f| %>

<h2>商品　新規登録画面</h2>
  <%= f.attachment_field :product_image %>

  <h4>商品名</h4>
  <%= f.text_field :product_name %>

  <h4>商品説明</h4>
  <%= f.text_area :caption %>

  <h4>ジャンル</h4>
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "選択してください" %>
  <h4>税抜価格</h4>
  <p><%= f.text_field :tax_excluded %>円</p>

  <h4>販売ステータス</h4>
  <%= f.select :sale_status, Product.sale_statuses.keys, :selected=>Product.sale_statuses[@product.sale_status] %><br>

  <%= f.submit "新規登録", class:'mt-2'%>

<% end %>  
</div>

app/views/admin/products/show.html.erb
<%= render 'layouts/a_header' %>
<div class="container">
    <div class="row">
        <div class="col-lg-4 mt-1">
            <h1>商品詳細</h1>
            <%= attachment_image_tag @product, :product_image, :fill, 300,300, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "300", :height => "300" %>
        </div>
        <div class="col-lg-8 mt-5">
            <table>
                <tr>
                    <td"><label>商品名</label></td>
                    <td>
                        <%= @product.product_name %>
                    </td>
                </tr>
                <tr>
                    <td><label>商品説明</label></td>
                    <td>
                        <%= @product.caption %>
                    </td>
                </tr>
                <tr>
                    <td><label>ジャンル</label></td>
                    <td>
                        <%= @product.category.name %>
                    </td>
                </tr>
                <tr>
                    <td><label>税込価格(税抜価格)</label></td>
                    <td>
                         <%= (@product.tax_excluded*1.1).floor %>
                        (<%= @product.tax_excluded %>)　円
                    </td>
                </tr>
                <tr>
                    <td><label>販売ステータス</label></td>
                    <td>
                        <%=@product.sale_status%>
                    </td>
                </tr>
            </table>
                <%= link_to '編集する', edit_admin_product_path(@product.id), class: "btn btn-sm btn-primary mt-2" %>
        </div>
    </div>
</div>

app/views/admin/products/top.html.erb
<%= render 'layouts/a_header' %>
<div class="container">
    <h1>管理者画面 </h1>
    <h2>本日の注文件数
        <%= link_to @order_histories.count, admin_order_histories_path %> 件</h2>
</div>