config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations',
    passwords: 'customers/passwords'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  get 'products/:category_id/search', to:"products#search" , as:'products_search'
  resources :customers
  resources :products
  resources :shipping_addresses
  resources :order_histories,only: [:index,:new,:create,:show,:edit,:update]

  get 'carts/confirm' => 'carts#confirm'

  get 'carts/complete' => 'carts#complete'

  delete 'carts/destroy_all' => 'carts#destroy_all'
  resources :carts, only: [:index,:new,:create,:edit,:update,:destroy]


  namespace :admin do
    root :to => 'products#top'
    resources :products
    resources :order_histories
    get 'order_histories/:customer_id/search', to:"order_histories#search" , as:'order_histories_search'
    resources :customers do
      patch :toggle_status
    end
    resources :categories do
      patch :toggle_status
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	belongs_to :category
	has_many :carts, dependent: :destroy
	has_many :order_details, dependent: :destroy
	has_many :order_histories, :through => :order_details
	validates :product_name, presence: true, uniqueness: true
	validates :caption, presence: true
	validates :tax_excluded, presence: true
	validates :sale_status, presence: true
	validates :category_id, presence: true
	enum sale_status:[:販売中, :販売停止中]

	def tax_include
		self.tax_excluded * 1.1
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def top
     @order_histories = OrderHistory.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  	redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      redirect_to admin_product_path(product.id)
    else
      redirect_to admin_products_path
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
  	params.require(:product).permit(:product_image, :caption,:product_name,:category_id,:tax_excluded,:sale_status)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def index2
  end

  def search
    @products2 = Product.where(category_id: params[:category_id])
    @categories = Category.all
    render :index2
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to admin_products_path
  end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
  end

  def edit
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      redirect_to admin_product_path(product.id)
    else
      render "admin/products/edit.html.erb"
    end
  end



  private
  def product_params
  	params.require(:product).permit(:product_image, :caption,:product_name,:category_id,:tax_excluded,:sale_status)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render 'layouts/c_header' %>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="container main-visual">
                <div class="b"><img class="c" src="/assets/img_top.jpg"></div>
                <div class="b"><img class="c" src="/assets/img_top2.jpg"></div>
                <div class="b"><img class="c" src="/assets/img_top3.jpg"></div>
            </div>
        </div>
        <div class="container-fluid bg-3 text-center mt-5">
            <h3>商品一覧</h3>
            　　　　　　　<div class="row">
                <% @results2.each do |product| %>
                <%# category = Category.where(id: product.category_id) %>
                <%# if product.category.status =="有効" && product.sale_status == "販売中" %>
                <div class="col-sm-3">

                    <%= link_to product_path(product.id) do %>
                    <%= attachment_image_tag product, :product_image, :fill, 200, 150, fallback: "no_image.jpg", :width => "200", :height => "150" %><br>
                    <%= product.product_name %>
                    <%= product.tax_excluded %>円
                    <% end %>
                </div>
                <% end %>
            </div>
            <div class="text-center">
                <%= paginate @results2 %>
            </div>
        </div>
    </div>

app/views/products/index2.html.erb
<%= render 'layouts/c_header' %>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="container main-visual">
                <div class="b"><img class="c" src="/assets/img_top.jpg"></div>
                <div class="b"><img class="c" src="/assets/img_top2.jpg"></div>
                <div class="b"><img class="c" src="/assets/img_top3.jpg"></div>
            </div>
        </div>
        <div class="container-fluid bg-3 text-center">
            <h3>商品一覧</h3>
            　　　　　　　<div class="row">
                <% @products2.each do |product| %>
                <% category = Category.where(id: product.category_id) %>
                <% if product.category.status =="有効" && product.sale_status == "販売中" %>
                <div class="col-sm-3">
                    <%= link_to product_path(product.id) do %>
                    <%= attachment_image_tag product, :product_image, :fill, 200, 150, fallback: "no_image.jpg", :width => "200", :height => "150" %><br>
                    <%= product.product_name %>
                    <%= product.tax_excluded %>円
                    <% end %>
                </div>
                <% end %>
                <% end %>
            </div>
            <div class="text-center">
                <%# paginate @products2 %>
            </div>
        </div>
    </div>

app/views/products/show.html.erb
<%= render 'layouts/c_header' %>
<div class="container">
        <div class="product-img">
            <%= attachment_image_tag @product, :product_image, :fill, 300,300, format: "jpeg", class: "pull-left profile-img", fallback: "no_image.jpg", :width => "300", :height => "300" %>
        </div>
        <div class="product-text ">
            <h2><%= @product.product_name %></h2>
            <h4>商品説明</h4>
            <%= @product.caption %>
            <h2>¥<%= (@product.tax_excluded*1.1).floor %>(税込)</h2>
            <% if customer_signed_in? %> <!--ログイン状態でのみカートボタン表示-->
            <%= form_for(@cart,url:carts_path) do |f| %>
                <%= f.hidden_field :product_id, :value => @product.id %>
                <%= f.select :number, [1,2,3,4,5,6,7,8,9,10] %>
                <%= f.submit "カートに入れる" %>
            <% end %>
            <% end %>
        </div>
</div>